### ISSUE TITLE
Input Fields & Iconography, Sign In Page lofi and hifi (desktop), Forgot Password Pages hifi and lofi (desktop)

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#10]

**Comment by BernieOyakhire** [comment]
Style Guide Iconography - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=517%3A400
Style Guide Input Field - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=525%3A220
Wireframe Sign-in Page (Desktop) - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A1995
Lofi Sign in Page (Mobile) - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3106
Lofi Sign in/Reset Password - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3158
Lofi Sign in/Reset Password/Error - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3169
Lofi Sign up Page - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3139
Lofi help page (mobile) - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3179
Lofi Sign in page (Desktop) - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A15874
Lofi Sign in/Reset Password - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A15943
Lofi Sign in/Reset Password/Error - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2564%3A1942
Hifi Sign in Page (Desktop) - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A5864
Hifi Sign in/Reset Password - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A6036
Hifi Sign in/Reset Password/Error - https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A5891
