### ISSUE TITLE
Colour System & Alerts/Notifications, Learn Page 2 lofi and hifi (desktop), API Documentation Page hifi (desktop), Landing Page lofi and hifi (mobile), Final Design Review

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#11]
Upload your frame link. Copy the particular frame link, you need to click on the frame you are trying to share before copying the link. The notification will be 'frame link copied' and not 'file link copied'.

**Comment by Spiritbck** [comment]
By B.Clinton

Color Systems
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=599%3A317

**Comment by Spiritbck** [comment]
Alerts
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=599%3A317

**Comment by Spiritbck** [comment]
Notification
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=599%3A317

**Comment by Spiritbck** [comment]
Learn Page Desktop
Hifi: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2583%3A4174
Lofi: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A15681

**Comment by Spiritbck** [comment]
Hifi API Documentation page
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A9724

**Comment by Spiritbck** [comment]
Mobile Pages
Hifi: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2615%3A5215
Lofi: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3658
