### ISSUE TITLE
Radio buttons & Checkboxes, Create QR code pages wireframe, lofi and hifi (mobile)

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#12]
Copy the particular frame link, you need to click on the frame you are trying to share before copying the link. The notification will be 'frame link copied' and not 'file link copied'.

**Comment by Prisca-line** [comment]
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=610%3A157

**Comment by Prisca-line** [comment]
Radio buttons and Checkboxes
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=610%3A157

Wireframes for Dashboard (Mobile)
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A2706
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A2742
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A2780
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A2803

Low Fidelity for Dashboard (Mobile)
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3382
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3269
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3010
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3054

High Fidelity for Dashboard (Mobile)
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A13475
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A13596
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2616%3A2285
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2616%3A1997
