### ISSUE TITLE
Design a functionality for the QR code when scanned

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#13]

**Comment by dPetersLib** [comment]
![2022-08-01](https://user-images.githubusercontent.com/40390930/182169473-2f8aecc9-c60c-4476-9d96-51484a1367df.png)

Scanning the QR code will download the file on the user's device.
since it is not hosted yet, the server and the device scanning must be on the same network for it to work. This is because the qrcode points to the file's download url which is on the server and would not be externally accessible otherwise.

**Comment by Oluseyi18** [comment]
Awesome work chief💪

**Comment by dPetersLib** [comment]
**Merging the frontend to the backend for Home App**
**Link:** https://github.com/zuri-training/Team-59_QRGen/tree/home

![Image](https://user-images.githubusercontent.com/40390930/183783108-30f5ae8f-c319-4130-8e1b-3965fa91547f.png)

**Comment by dPetersLib** [comment]
**Created the API using Django Rest Framework
Link:** https://github.com/zuri-training/Team-59_QRGen/tree/api


![Image](https://user-images.githubusercontent.com/40390930/183783604-514e23f4-7888-4cce-a57a-beebe5a3df5d.png)

**Comment by dPetersLib** [comment]
**Merged a pull request for the completed accounts branch
Link:** https://github.com/zuri-training/Team-59_QRGen/commit/ffb3b6a35fff58e89c9b98606023335e58d70bb3

**Comment by dPetersLib** [comment]
**Created the Database Scheme for our project and added descriptive comments to it
Link:** https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&layers=1&nav=1&title=ER.png#R7V1tl5q6Fv41rnXOB128COLHGWdsz5qXTqczt7f3y6wIUTlFsIDj2F9%2FE95UEjAIoiV09ZwqhhCyn%2Bz97J2dpCOPFh%2BfXLCcPzgGtDqSYHx05JuOJMmaoqF%2F8JVNeEWS1WF4ZeaaRnhN3F74Zv6G0UUhuroyDejtFfQdx%2FLN5f5F3bFtqPt714DrOuv9YlPH2n%2FqEswgceGbDizy6nfT8OfRVTF%2BDfzDZ2jO5tGjNWkQ%2FrAAceHoTbw5MJz13iX44Y8d24%2Ba%2BATdBbCh7aNfHoD7E7od5Xbu%2B%2FhNrzrSGP2d4tK9mePMLAiWptfTnQW6rHuoyHgKFqaF%2B3mnouuoIvQ4%2BbYjj1zH8cNPi48RtLCwYjGEbRpn%2FJr0g4vrZbhh1H3f3P8UfPvzWv6P%2F%2FAwexpMulJYyzuwVlH%2FfnVHCDRRD%2FmbuNtRZy3xRx9M8KVrzweuH6FDFtAFJG8fmDZ6NflGDL5bFlh6ZlA8vDI3LeMebJyVH1cUf7uemh%2FQeA7BgcsinNyjyvBXXDnu5m9RY%2FDPwDJnNvqso3fHT7x2oYfacg88PyoR3BE2T1SDB1jWyLEcN3gdearpUNeD93Cdn3Dnl4mm9BUhaMLKNqAR1Uf2diSAd%2Bj68GPnUtT7n6CzgL67QUWiX9V%2BhLJo6A2ir%2BstjOUYiPMdBMtxQRDhcpZUvRU3%2BhBJvID0ZUL6mXJHb%2B6bwHpGQxrYswAC%2BxLGXWa4zvIFuDPoRxeWjokFdPsOw0ElpCRhOzaMiwUvp1yjv%2Bh1R0JP6SioASP0Xdx%2BR39xcdcfOTYSHQIcfhREcl9DLPtr31lGz7HgNG6GG3Um%2FjxxfB%2BN0Rhm%2BTLOHTOHBR8JWmYV9Knk3Cfk%2FHRXRNIOetepFejKuWkY0A7HO9bvYCt9imCp0kgkkBZNepQfJR2ZWTq74igojaiybR8Vrg1YaFzYwIfX%2BCU9QsRJO4%2BXukJIXUea%2FQ3dc3mijxV6WPbaWwLdtGf34Z1qChvK6bHx0ckauaJQKVaYqqsWLLpj3vs3gxfxSnP%2FJ%2F0yfz8%2B%2FuiKIkkFsHJtocIIFZGClUGlUGGprRakqARSHr%2B8oAuPr%2Ff3LWBYASMJFOVSlBYcUC4s1dVgiUjAcMQzWXyJanimem6eOSDkPL4TL1AjHCUOlVkcTSeWGiHmlQddTCxHUudKuECBFzIBR7se7AjhkF6SsYYG0Mv6oMIRvSStSHPoZX2AaSa97BpP7uzO1h0NfpLk0Tfr7nHWbenkSejksEY6SZcraTPGd9LFkoxDUsnFLl%2B0kt4VZJja3yybELBk0fpl0dFkSknvGzK%2BzQmjrAgqTaSU9K5pcsCyRsA0k1JSvRByMqSlmCegmIm46%2BCYVEGXS4G4EGaZC2GuiCW1J0heaS5mbyvXukBRV677S2KjybQyI%2F5EyZuYA%2FcvSVH%2BbgHDM7nMwMuQc3ZZDWCaSS6pNIkETEsuT0EulXPPh8c58382u8zFMFfski5kkRAy0H3TsXlhmCXxwSHDJB0SrhhmNYDhiGGSCTd8McxqANNMhvlZuzVW10v3%2B%2FJD%2FAw3b7IN1l2JzKFoKeYpKKZWI8WkS5rUDReoEQ5JIx%2FEXHFMeleQLmPEMfEM%2BQUKvHITUBYhTWaZ1L6JH5kmmTIXFLMiuDSRY9LRQjqxfFHMigDDEcdUW45ZC8dMdt44G8dUm8sx1ZZjJl1BckxPB%2Fabjp7IRVpdWYBwRzEHJMXkJAOzIqhwQy8HJL28uR1fvd5zTzGLg4YjijmQCNi0FPMUFLN%2Fboo5aEQeZj6IW4o5ICc%2BDfTAtxkS2OVJux4DUAAe%2FBFMMhUT46XFSsswia7hfY1PRYDhiV22Acx62CXzRqcnY5fNDWAO2gBm0hVkANP03vA8%2BTvHlKGNX2b2TZy8swOYieNYEHDsjbQxzEy05E%2BRo0pRmxALlUUsrm148%2BX59bbFU0tAyc4ZtuHNmvZfPzcBHdJ2MpIvUCscNciH7BJpOgcdkhFOJBNe9jAqiw7uGOiQ2z2MKoIKN%2BxzSMY32xn0I0HTTIr5OFJ%2Bej%2Fcp4U5fP70ZrgPsnDbJX2WlmGegmFS1NDJGCZV0OVciQthl7kQ5opcUnuCdCJ807e4iG2WREaTiSW1azJWmCsCF6t%2FqkFLE7kltWdIJ4QpsPlqB%2BqHC8%2B2GkQ1k3jSKRRprF698NxTKlbac0WPPlc0EW%2F2uaLJXu67qBCHFZBRuvBJ81NESfzhbsfxB4uynyGWfbIoVdQn2%2BGKsgl3c48WTWDNlStC7woyHBWfAXV5wq%2FnAMAC6GiyO0Lfwkgg8cJJoLsirDTRGcmACpmVw1cmb0WIoTkbRblBPmJYaqvDFrV5vPWwTcr5ojWzzUbk8eaDuOWWlM2upqbr%2BW82WHAR7C4LEA7pJWkCeIp3VwQYjjgm79tdVYSYJnJMKmLIMFdLMU9BMSlnjp6MYlIFTcYpLlAdHHUih8IsiwYRTGpPkGTBAhzRy5Lo4JBdkm4nT%2ByyGrxwRC4lzsllNYDhhluWC2q13LLMYaP1kstyB39dMrnUmIXRdHJJOfMLLoDJxUlQJaHBIbMkNQL3zLIwXjhilmRSZcssiwOGG2ZJOZqwpZYnoZaUo0brpZYi6XReoEI4anyL7BnRjSeXpAFYAs9bO65xgdKuR%2F0XgAd%2FBJPijXBPMIsDhiOGSa7caBnmEYjhhmIqDDPj0JjBWAYQLxrcPEML4OMLb7e%2F7K2sQi9%2FPfcXViQmaBtXrhuA6fYZweTFeQD2phOtFtv%2BtAC28SVA0b6YicVYw6GA%2FoQ1j038xgGaSDhEgveclavDPMoYjRs%2FJsdZBaP5ZdwlrEyGakySi27Qle9wr705cHpygsT7GKiD1OIxuZ%2FCUPjq0V1b%2FBAVaamKpHRFYdcQFR0BxK7x5M7ubN3R4CdJHn2z7h5nlJ0uvroveYdjtisOj15xqCr7slZox%2BCKeagt4%2F9QxV%2FO%2FfnDPV0Ww5Y7aMosOKQKugo%2Fl9pi0gFqxHrDXExz5fdSe4Jkpfjc4wasNqwBG012eqldw%2B2eetUApYnOLrVneD8xpBq4UPc0KUoJDigWlupqAEy7zrAWjklZZlgvx2zEKsNcBLeMkky84CX9uyQwuKOTWVMoosjFFEo1cOGGVFJSLlpWWRwvHLFKyvYVY9Nq49Y17JTXFxUCZZJGgYV4Mq5ZckuLP9ypON5NZdcoOVvl0UR9OkmTlLPBoWsuFwTQZyxI%2FsjRkTBl0cGduyGTBJLr8HW7HCATKRKBlNbVOAIwNF%2BjKDPIBwxLbXUAhpw854hrHh00Lc41aRvl1co1ZXLCfHwnFhH2JUexZfb1GY0nl%2BRkd0P2YT7aABRAB3%2FkktttmCuCCj%2FkkoxKtuTyCMDwQy65DmTWSC5pW%2BTVSy4bsY1JPohbZhkv39hlli4Xu5iURQZ3rLJPhiyDDAlJUfhNkSgOGG64Zb8NXFYCGG64Zb%2FgIlNE6ebOzLGBVdMCU2hNghJYdqYOrKBK9M7%2FjRAUfPmBv%2FSU%2BOvNx%2B6PNxsKWnPTJJI1rCS%2ByqxazfV7LmbZanLgdrwByyCFSuZlq8P9ipJM4wPLVhEmwGanWOR1ZDZYVFMNjlJPstqVLt%2BP2rkdWWELqh1nDLtfn30xN2WslRwbeQshDg6NuIsuZmikV3T30wqbdWgMtBRk0%2BeFVrei%2B7N2a6yul%2B735Yf4GW7eZBusuwrpgXQk1cImeII%2BzPCHr%2B7IMWAP6BiAb36w3jssgh6ZlEpuc7OvvMxND0PFdd5NA%2BKP8MN3AfoX59WhzwFoMCLmAH9ezxHdwN9gUMTA%2FwQ1GBsbLEy9hz7%2BE9w0d1aWgYUN3mFyx9SxEHFBNALfPXdMHWfaXbE0NL5imO%2FpSyZxV3xhDdFHoYv%2B%2Bw4nnunjJrw%2B3%2Bd1FrpG1IeuUR5bqCWY24QteQk6tfYGLI1p1ICnm%2FEZng%2Ff%2Fej5QSTrDC2YmL%2BjFlyvPJzjiWE7Aq5xhraswTIGJhpXHlguz9AIczGLGvHPAszw4K8fFQsrRkW4W2ztLcjWNJU1ItKxOsCacxJozMXSggucQ4w1pLnVqMa%2FyB3B6naBVCvuGoxULKXlBnH7oNwK3YqrQzxhp1ykTHtZjcrwLm3Hx1TDizgLZum5bp%2BI2cUOq1nPkVL9horg29cuQjW64yf09Tmd1xsK1Ix%2Bh8JdNGkiq2rS1lIJz6LYT9FbSlBKpTl5Uo7PyBo9plt1hj0pD%2FtyOyQycul3ZJHa%2FGdXColXJnYKeWWElAby8Fa5ypPSLsPM5Te7FJNaMJ4jOEgxP%2FYaUJJHDlObvEhpFyuD%2FpGuTNqXkRmdtcI%2BVrKkI26yesDJOnBDaS%2BLLndaGlZKGUeENoi4l%2BKzazNoUKBsIwL678rDfeCvsXp1lvhBdO5pTmN1rIIFVmj2xFueXYnGigGsfOdselVIAWe70%2BKuZlXy3LzqNSuZ9FWjZj2JhpRJDUkNZA3PoiBToSNRUJgUZGG1JgxSWkquQ0vRYq6E9413WOuFK6fPpqa6AcSRJHX6b5FDztIa7O4bcApW1p7nHjTLg0FznORpvVYvknwzFXxSKGeu0NWicjK1WDCoyaoW4YfpJ%2FF99HlLJBmpKLpnyzbxl83Olyfomuj9g8Wc%2Ber1WEpbQi0rpFrOW%2FZbr1oWBWkfgyqjXq5Mc9L2iaHGLY9VmldTDAz0Qui%2Fr884eLMTf5xBG7ogcKhHcZnoaYIz%2BRfqpGrTXYhv6LE8O%2BNVeuZiVoau%2BqQd2FG4YUxgCZAKCSKv7jaQ%2BsuNg684dBN3godsCO19Hh0%2FvDWI4YLgYb9wV%2B5W4pG633fcdITi4fbmH2SNhOcvwdw1hlHcGq%2B1BOnJgy419ECzBMTGsdVZAoYUxT%2BMIA8YCTLrJFWlmlhLRRC0evWwSos0pZQX3mmhV97LzmKKaX6Yvp2qQ4IFHHiJcKtGiB0baDsN1%2BxmqxInfLJg4srxWiweqIfTULRzqLGU960qp3Hzs6DOmiFSuLxUbUYJXbQMsc5XpO968NCsFwN53NfC0TxS4s1bzixgbwihIBwJWEcjyc2Dj2szIJfhXUGT4pN1mGjxS%2BppyfwV0p5znCejBzky6MJfSPnq81DPe5G6DyMo0UwWfu4SPfdv4pVwvqNrIrLdGob0aOkmGWAHLYN2MstwokhDLfwy72i9gzNUKmt%2BYKWKmcBAetKSdYYqXVGaqFY1P5UKGEviAY2dKt%2FVatDYGm0WIT07tVwGkVjk7s5wFhRNaxdXUMlWYsVV1GGtNJ1OJXoe7Xh8rQxyCUyBgzHSuXeUxVrJMdS7SulkPq9WMHU6JqPZ9LTX3yWo6LMBvHmiko7UVYkQwl%2B%2BR90l7fHRnpRw0B%2BdnXhn5YQ0HgMX6lan5h77jCnLlWmIgmYuE1InBk618s%2Fb27rmecd0To9ab1xFo4XRsiwE0HUkTT8jpY5LIyGf3ygwrOD9w0cwhbnmnvVb7xDuD5UeIguiMtCG%2FYGsDvcGdM3jechwrkG1qz62SzvOcYBf7rZhB12dIavNr2u9h5IyB%2F1jT%2FBT00uOGBP%2BqsKhKGQH7IMU3h1Aqr9WThD5gR9%2BN7IN2Nwk5mFbhDJxSaloAvSfswB0XT2EGa7OtE285pRaH44RoSLdbhLmjx4jHJ7czcmUrugliVAV%2FZFEyy6wo7FCkISXL%2Bh%2FwUoxSYh1jzc3Dy0XoLwzrWSFr42IiV3Rm%2F%2BFBkQQH%2BzESfNRbtQi7IcQaN7fO28WPj2%2FGy44dgigNqUSMFXX4GRaDQFTpHTskLbbPO2A3dPNKtFOXiatcFWhQVW9lsZjKufas8i6BTzP1F%2Fmph3%2FFFnb3B3ZDxrRRNUXsaK0YK5SkQ1NL3U8es1kOqH8dKfgZnRsdtrmBar2JDEp0O7xgb2t3aykcyNjGXRtaEO5sZsPe%2FYxbT2doDNCtLW2s5jtFBMTmF7Mc07byRKRvCzbeWyWRfAtncxRxhArF2WI02sqjnZmRTGVfJZ4t7VZ4uw04As0FvuWODyAqLXDVfuvnJnhL5GhzbbC6QTJKAUmyM5eOMECoC%2B2tUmMNgZma7ILzjekl4%2FR5h%2FqttgsqdiXarF7AzWZmA4monvCobnoys0269Ka8%2FjP%2FXQmDqvZ7qewqsn1zoWIAsvU2KUCc49K7iESj%2B9dTCqDLdOsEJZx9ONCYElsPBCrnaKw7KbIpFJ3WIdyCO0FM55oaqSlkiekkrxNhYSv%2Fpo9GYKB1k6FFOSG3XQ4J1G9tZDDja8a6vvYBuPBzfrOtt5%2BDa0ubRY4Jx3hXMkp24TI4UDrbFMiu0JPEOIC7AtyqIbzuFwGmTWXIcxzO%2FXyGXXQEzQ5%2BaPsW1LGTSUpMy3Dnqhu%2F4j5BjrD0h820Oir62BVtC2OxvP8IdhuTL79Pw%3D%3D

**Comment by dPetersLib** [comment]
Closed Pull Requests
https://github.com/zuri-training/Team-59_QRGen/pull/56
https://github.com/zuri-training/Team-59_QRGen/pull/53

**Comment by dPetersLib** [comment]
**Redesigned the QrCode Generation functionality to be more effective.
Link:** https://github.com/zuri-training/Team-59_QRGen/tree/qrgen2



![Image](https://user-images.githubusercontent.com/40390930/183784889-89c5774c-648a-4ad3-a407-c193602aa875.png)

**Comment by dPetersLib** [comment]
**Links:**
https://github.com/zuri-training/Team-59_QRGen/tree/handlescan
https://github.com/zuri-training/Team-59_QRGen/tree/home
https://github.com/zuri-training/Team-59_QRGen/tree/api
https://github.com/zuri-training/Team-59_QRGen/commit/ffb3b6a35fff58e89c9b98606023335e58d70bb3
https://github.com/zuri-training/Team-59_QRGen/pull/56
https://github.com/zuri-training/Team-59_QRGen/pull/53
https://github.com/zuri-training/Team-59_QRGen/tree/qrgen2

**Comment by dPetersLib** [comment]
**Hosted the project to Heroku**
https://qrgen59.herokuapp.com/


![Image](https://user-images.githubusercontent.com/40390930/185801773-a11740d3-9933-42a4-af03-71a2e12bf860.png)
