### ISSUE TITLE
Generate QR code with Python (Django)

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#14]

**Comment by Lisaojet** [comment]
I have carried out the task. The qrcode file ouputs the qr code generator and it works in Python. When you run the python file in the terminal, there will be a prompt to enter your string and a button to generate the QR code.

**Comment by Oluseyi18** [comment]
Welldone!

**Comment by Opetimistic** [comment]
Developed and Created the Django project's structure and uploaded it to the master branch on Github.

https://github.com/zuri-training/Team-59_QRGen

**Comment by Opetimistic** [comment]
Developed and Created the Django project's structure and uploaded it to the master branch on Github.

[project and app structure folder- first commit']  (https://github.com/zuri-training/Team-59_QRGen/commit/112534fec6756bc52a65ec997c707b201705140b)

![Image](https://user-images.githubusercontent.com/23134664/183706744-6c7d4709-a285-41f4-810a-afb55469f2b1.png)

**Comment by Opetimistic** [comment]
Contributed to documentation in the README.md and Google Docs.

https://github.com/zuri-training/Team-59_QRGen/blob/master/README.md



![Image](https://user-images.githubusercontent.com/23134664/183823355-3014aee6-51db-4baf-a99c-8d17f8feda6f.png)

**Comment by Opetimistic** [comment]
![Image](https://user-images.githubusercontent.com/23134664/183823445-11451c5b-d97f-4392-9a9a-913874395a88.png)

**Comment by Opetimistic** [comment]
![Image](https://user-images.githubusercontent.com/23134664/183823527-bd8a20ea-ff4e-4eb2-895c-958d56be408d.png)

**Comment by Opetimistic** [comment]
![Image](https://user-images.githubusercontent.com/23134664/183823573-de88f927-fa2b-4572-865a-cfbe278a790e.png)

https://github.com/zuri-training/Team-59_QRGen/blob/master/README.md

**Comment by Opetimistic** [comment]
Worked on the generation of QR codes using python(Django)

https://github.com/zuri-training/Team-59_QRGen/tree/opeoluwa/qrgen

![Image](https://user-images.githubusercontent.com/23134664/183963882-ace980d3-e98b-45f8-9420-b249f1437be9.png)

**Comment by Opetimistic** [comment]
![Image](https://user-images.githubusercontent.com/23134664/183964362-4b471729-19c5-4c33-8031-edb7419cba4a.png)

**Comment by Opetimistic** [comment]
![Image](https://user-images.githubusercontent.com/23134664/183964437-053f2ba1-e256-4bc4-b770-c0c434eabb08.png)

**Comment by Opetimistic** [comment]
![Image](https://user-images.githubusercontent.com/23134664/183964500-27f84f27-cf14-40ec-b821-adef16f4bad8.png)

**Comment by Opetimistic** [comment]
![Image](https://user-images.githubusercontent.com/23134664/183965469-cad7a893-589a-418d-af29-a3e9d6db00a2.png)
