### ISSUE TITLE
Convert the QR code file to different file types and pictures (PDF, PNG, JPEG)

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#16]

**Comment by KomaConnect** [comment]
1. Built functionality for the QR code to be shareable in different format (PNG, JPG, PDF) - https://github.com/zuri-training/Team-59_QRGen/tree/opeoluwa/QR%20gen%20sharing%20format

**Comment by Oluseyi18** [comment]
Great job boss!
