### ISSUE TITLE
Authenticating and saving user's login information & API Documentation

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#18]

**Comment by oluwasegun31** [comment]
Authentication and saving users login information
[https://github.com/zuri-training/Team-59_QRGen/tree/accounts](url)

**Comment by oluwasegun31** [comment]
Api Documentation pages
[https://github.com/zuri-training/Team-59_QRGen/tree/oluwasegun](url)

pictures
![Image](https://user-images.githubusercontent.com/105318972/183642524-e97f7f6b-0cef-40d3-96d7-290c7bf44ed0.png)
![Image](https://user-images.githubusercontent.com/105318972/183642525-d2966562-7b41-4966-98a9-292b7197ed27.png)
![Image](https://user-images.githubusercontent.com/105318972/183642523-5baab982-0912-4c0a-98d0-2d564d1bf249.png)
