### ISSUE TITLE
Research Objectives & Questions, 1st Learn Page Lofi and hifi design (desktop) (before review)

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#2]
Upload your file link.

**Comment by KenAkand** [comment]
Another reminder, upload your work here or a link that leads to it.

**Comment by Fawibe93** [comment]
Research Objectives
At the end of this research we want to ensure that users (beginners) will be able to navigate through the QR gen platform easily as the current platforms are not very easy to use for beginners which negatively affects user experience as the user gets frustrated while using the platform.
To build a QR gen platform with usability in a more simplified way with less hassle which when scanned will lead to the user’s portfolio website or catalogue.

Research Questions
- How do you currently use QR gen? (Behaviours)
- What challenges do you face when using QR gen platforms? (Pain points)
- What factors affect your usability of QR gen platforms? (Pain points)
- What are your perceptions of QR gen platforms? (Behaviours)

**Comment by Fawibe93** [comment]
1. Research Objectives and Questions:
https://docs.google.com/document/d/1y_3mSl2IU5cK7TO2YDTX75EdKpwPnRJDHncSCPuNVTw/edit?usp=sharing

2. First Learn Page Lofi:
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A16155

3. First Learn Page Hifi:
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2583%3A4174
