### ISSUE TITLE
Build the dashboard

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#21]

**Comment by ScottDeev** [comment]
![Screenshot (123)](https://user-images.githubusercontent.com/99127718/181904465-035305f6-9853-47f6-a843-3cf0ade3c4ad.png)
![Screenshot (124)](https://user-images.githubusercontent.com/99127718/181904476-c0a7b1dc-924b-4cd2-80d9-87e01e9eaeac.png)

Current updates
![Screenshot (125)](https://user-images.githubusercontent.com/99127718/181904494-328555b7-1f37-4e33-9863-6aa239dcf67a.png)
![Screenshot (126)](https://user-images.githubusercontent.com/99127718/181904523-445c25b2-43d2-466f-9e26-6d93d81e2777.png)

**Comment by Oluseyi18** [comment]
Welldone Boss... Keep up the good work!

**Comment by ScottDeev** [comment]
Done

**Comment by ScottDeev** [comment]
Dashboard branch

**Comment by ScottDeev** [comment]
>

**Comment by ScottDeev** [comment]
Done 
https://github.com/zuri-training/Team-59_QRGen/tree/scottDev

https://github.com/zuri-training/Team-59_QRGen/tree/main-dashboard-template
