### ISSUE TITLE
Screener questions & Test, Contact Us Page lofi and hifi design (desktop)

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#3]
Upload your file link
Favour, another reminder. Upload the screener questions here or the file link.

**Comment by favourp** [comment]
[https://forms.gle/MnSxVpybmRsLkpHVA](url)

**Comment by favourp** [comment]
Screener Questions 
[https://forms.gle/MnSxVpybmRsLkpHVA](url)

**Comment by favourp** [comment]
Contact Us Page lofi
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A16853

**Comment by favourp** [comment]
Contact Us Page hifi design
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A7458
