### ISSUE TITLE
Support/help page lofi Design (desktop)

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#31]

**Comment by KenAkand** [comment]
Support page: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=1496%3A2160

**Comment by popoola41** [comment]
Help page: lo-fi https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=1496%3A2160
