### ISSUE TITLE
Build the registration page

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#32]

**Comment by Oluseyi18** [comment]
Work with @ScottDeev to build this page

**Comment by Lisaojet** [comment]
I wrote the code for the HTML and Scottdev did the CSS. We are waiting for possible changes from the designers before we make final conclusion.

**Comment by Lisaojet** [comment]
This is the link to my branch on the group's Github.
https://github.com/zuri-training/Team-59_QRGen/tree/Elizabeth

**Comment by Lisaojet** [comment]
![Image](https://user-images.githubusercontent.com/105356867/183929863-bc3082bf-fbff-4ef1-9930-2d0e01fc3dd1.PNG)
![Image](https://user-images.githubusercontent.com/105356867/183929862-47e5a359-39cc-45ae-9643-8c9a6d34c72d.PNG)
![Image](https://user-images.githubusercontent.com/105356867/183929867-7d7bd821-c0a2-4352-9fef-a45440ed41cf.PNG)
![Image](https://user-images.githubusercontent.com/105356867/183929864-8d1b1832-f6ee-43af-b3da-c8b2352de928.PNG)
![Image](https://user-images.githubusercontent.com/105356867/183929865-d69d1ec7-9314-44f5-9db9-0f7404564150.PNG)

**Comment by Lisaojet** [comment]
Sign in Page

![Image](https://user-images.githubusercontent.com/105356867/183930566-9e5430e1-1ff0-4d51-b344-8eb41c4b01f2.PNG)

**Comment by Lisaojet** [comment]
Sign up page


![Image](https://user-images.githubusercontent.com/105356867/183930730-be1893ea-ab4c-4eef-998c-055eddcd52a4.PNG)

**Comment by Lisaojet** [comment]
Forget Password page

![Image](https://user-images.githubusercontent.com/105356867/183934834-8c58aca1-5794-4f1d-a5f5-0842a751839a.PNG)

**Comment by Lisaojet** [comment]
QR Code Generator

![Image](https://user-images.githubusercontent.com/105356867/183946530-6dbcf6c7-8708-4c92-861f-fa34fcb899e7.PNG)
