### ISSUE TITLE
Interview Script, Carry out interviews & Analyze interview feedbacks, About Us Page wireframe, lofi and hifi design (desktop), Signup page wireframe (mobile), Sign In page wireframe(desktop), dashboard 1 page wireframe (desktop), Contact Page hifi (mobile), API documentation hifi (mobile), Final Design Review

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#4]
Upload your file link

**Comment by MO669** [comment]
Interview script.

Written by Mohammed Ayobola, Co-Written by Ekima Inetimi.

Hello, and how are you? Thank you for taking the time to participate in this research study. My name is Mohammed/Ekima.

The purpose of this research is to learn and understand the experience with QR code generators. From our first survey, you gave a positive response to the question “Do you know what QR codes are?” we suppose you do know what QR codes are, if you don't know what they are we will be more than happy to explain what they are and what they can do for you.

We will begin the interview shortly, it promises to be interesting, we will be asking you a series of questions. The interview will last a maximum of 40 minutes, however, if you wish to call it off or take a break - you are at liberty to do that.

Before we begin, we want you to know that this interview will be documented for reference and educational purposes, we would like you to know that this interview is not a test of your knowledge - let us know if you have any questions.

Creating rapport - Section 1;

* What do you love about your job? 
* Tell us about the type of company you work for and your role there. 
* What would you say is the hardest part about your job?  
* What does a typical day look like for you?  
* What do you like to do during your commute? 
* How do you relax after a stressful day?

Finding out behaviours and motivations - Section 2;

* What mediums do you use to tell people about your services?
* Do you scan QR codes found in public places? 
* Are you ever sceptical about scanning QR codes in public places? 
* Do you think QR codes are a good way to store information and advertise? 
* Have you ever stored information in QR code format for others to scan? Why/Why not?
* If your answer to the previous question is yes, what platforms did you use to generate your QR codes? Why did you choose this platform?
* Would you add QR codes to traditional modes of advertisement? 
* What do you like the most about QR codes?

Finding out pain points - Section 3;

* What problems have you encountered while scanning a QR code?
* When you use a contemporary advertising medium what challenges do you face?
* What challenges do you think advertising with QR codes could have? 

Finding out tools in use - section 4;

* How do you get a potential client or customer to see your previous work?
* What mode have you used to advertise your services in recent times?
* Are there any features you would like a QR code generator to perform?
* Which advertising medium has been the most successful for you? 

That would be all for now, thank you for your compliance. We appreciate the opportunity. If you have any more suggestions or you feel we left something out, reach us at ayobola560@gmail.com - kiminetimi@gmail.com or call 09071364631 - 09065930310.  Enjoy the rest of your day.

**Comment by MO669** [comment]
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2566%3A2029 - Hifi 'contact us page' mobile.
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2566%3A2029 - Hifi 'API DOC.' Mobile.
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A6163 - Hifi 'about us' Desktop.
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A15954 - Lofi 'About us' Desktop.
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A2088 - Wireframe 'About us' Desktop.
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A2046 - Wireframe 'Sign up' Desktop.
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A1995 - Wireframe 'Sign in' Desktop.
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A1798 - Wireframe 'Dashboard 1a' Desktop.
https://www.figma.com/file/rKPKtW9r3j4wVzv8p4WHeX/Team-59_QrGen-Figma-File?node-id=0%3A1 - Proof of final design review.
https://docs.google.com/document/d/10lS_afiZtfweq3EzA_EMmd287hWCSeSTAuENMwCa_RY/edit - Interview Script.
