### ISSUE TITLE
Convert the QR code file to different file types and pictures (PDF, PNG, JPEG) 

### ISSUE THREAD

**Issue by AEedriz** [zuri-training/Team-59_QRGen#45]

**Comment by abdulgiyath** [comment]
Yeah,

**Comment by KomaConnect** [comment]
![Screenshot_20220809-221020](https://user-images.githubusercontent.com/88900346/183763986-7798f6f5-82a5-46ba-936c-730fb9ef159e.png)


Waiting for ope to implement the change on generating the qrcoe so I can put in the code for converting it

**Comment by AEedriz** [comment]
Ok
