### ISSUE TITLE
Link the QR Code Generator to the dashboard page

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#47]

**Comment by Oluseyi18** [comment]
Work with @dPetersLib and @ScottDeev to link up appropriately

**Comment by Opetimistic** [comment]
I am done with the qr generator and pulled from @ScottDeev 's branch. Waiting for Scott to update the dashboard page

**Comment by Oluseyi18** [comment]
Alright then. great work!
