### ISSUE TITLE
Empathy Map, Learn Page 1 wireframe, lofi and hifi (mobile)

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#5]
Upload your file link

**Comment by Oritoke1986** [comment]
Empathy Map https://www.figma.com/file/N0Q8o15s5inpvlNN43lQ2C/Team-59_QrGen-UX?node-id=0%3A1

**Comment by Oritoke1986** [comment]
Empathy Map https://www.figma.com/file/N0Q8o15s5inpvlNN43lQ2C/Team-59_QrGen-UX?node-id=0%3A1

**Comment by Oritoke1986** [comment]
Wireframe learn page https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A2654

**Comment by Oritoke1986** [comment]
Lofi learn page mobile https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2594%3A2107

**Comment by Oritoke1986** [comment]
Hifi learn page mobile https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2586%3A3468
