### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by Oluseyi18** [zuri-training/Team-59_QRGen#54]

**Comment by dPetersLib** [comment]
https://viewer.diagrams.net/?tags=%7B%7D&highlight=0000ff&layers=1&nav=1&title=ER.png#R7V1tc5u4Fv41ntn9YI8Bg%2B2PiZO0O3lpmia3t%2FdLRgHZZovBBRzH%2FfVXAoFtJLAwL3YRO%2B0WMAih8%2Bic5xwdSR1lsvj45ILl%2FN4xoNWR%2B8ZHR7nqyLKsjhX0D76yCa9I2oBcmbmmQa5tL3wzf0NysU%2BurkwDens3%2Bo5j%2BeZy%2F6Lu2DbU%2Fb1rwHWd9f5tU8faf%2BsSzCB14ZsOLPrqd9Pw5%2BSqpI23P3yG5mxOXj2Sh%2BEPCxDdTL7EmwPDWe9dgh%2F%2BjWP7pIqP0F0AG9o%2B%2BuUeuD%2Bh21Gv576Pv%2FSiI9%2BgP1N8d2%2FmODMLgqXp9XRngS7rHrrlZgoWpoXbeaegS1IQep1y3VEmruP44dHiYwItLKxIDGGdblJ%2BjdvBxeVyPDDpvm%2FufvZ9%2B%2FNa%2BY9%2Ffz97HL515bCUd2CtSPt%2BdScINKSF%2FE3U7KixlvjQB2%2F40qXnA9cn6FD66AKStw9MG32aciUF55YFlp4Z3B5emZuWcQc2zsqPCorOLqfmBzSeQnDgexFO7lBh%2BBQXjpv5G6kM%2FhlY5sxGxzr6dvzGSxd6qC53wPPJHcETYfUkLXiBZU0cy3GDz1GmIx3qevAdrvMT7vzyNlIHaj%2Bowso2oEHKo1ubCOAduj782LlEWv8TdBbQdzfoFvKrNiAoI11vSE7XWxgrERDnOwhWohsBweUsLnorbnRAJJ5D%2Bgol%2FVS5oy%2F3TWA9oS4N7FkAgX0J4yYzXGf5DNwZ9MmFpWNiAV2%2Fw7BT9ROSsB0bRrcFH6deoj%2Focyf9ntpRUQUm6FzanqM%2F%2BHbXnzg2Eh0CHH4VRHJfQyz7S99ZkvdYcBpVwyWNiY%2FfHN9HfTSCWbaMM%2FvMYcETQSu8gq5KzgNKzo%2B3eSTtoG%2BdWoGunJuGAe2wv2P9DrbSZwiWKY1YAknRJHv5UdJRuKWzK46c0iCFbdsod2nAQv3CBj68xB%2FpUSKO63m81FVK6jrS7K%2FomfMTfaTQw3svvSXQTXt2Fz6pJbChVo%2BNj9SeK%2FVLxQpXceWCRXfMO%2F9q%2BCxdjNz%2Fyb%2FM3w8PP7qSRFMBrFxbqHBCRWJgZVgqVHhKqwUpGoWUhy%2FP6MLDy91dCxhewMh9hnLJSwsOKBee4mqwRDRgBOKZPL5EOTxTOzXPHFJyvrmVzlAjHCUOjVscTSeWI0rMKw%2B6mFhO5M5F%2FwwFnssEHO168CNEQHpJxxoaQC%2Frg4pA9JK2Is2hl%2FUBppn0sms8urNbW3dG8JOsTL5Ztw%2BzbksnK6GT4xrpJFuutM24uZXPlmQckkomdsWileymoMPU%2FmbZhIAlj9Yvio4mU0p229DxbUEYZUlQaSKlZDdNkwOWNQKmmZSS6YXQgyEtxayAYsbiroNjMgVdLAXiTJhlJoSFIpbMlqB5pbmYva5c6wxFXbruL4iNJtPKlPgTI29iDty%2FZFX9uwWMyOQyBS9jwdllOYBpJrlk0iQaMC25rIJcqqceD49y5v9sdpmJYaHYJVvIEiVkoPumY4vCMAviQ0CGSTskQjHMcgAjEMOkE27EYpjlAKaZDPPz6NpYXS7d78sP6TPcvCo2WHdlOoeipZhVUMxRjRSTLWlaN5yhRjgkjWwQC8Ux2U1Bu4yEY%2BIR8jMUeOkmoChCmswymW0TvTJJMhUhKGZJcGkix2SjhXZixaKYJQFGII6ptRyzFo4Zr7xxMo6pNZdjai3HjJuC5pieDuxXHb1RiLS6ogARjmIOaYopSAZmSVARhl4OaXp5dX1z8XInPMXMDxqBKOZQpmDTUswqKObg1BRz2Ig8zGwQtxRzSA98GuiFrzMksPOTdj0GIAc8xCOYdComxkuLlZZhUk0j%2BhyfkgAjErtsA5j1sEvuhU4rY5fNDWAO2wBm3BR0ANP0XvE4%2BbvAlKGNX6a2TZS8swOYN8exIBDYG2ljmKloyR4iR4WiOiEWqkhYXNvw5vPTy3WLp5aA0o0zbsObNa2%2FfmoCOmatZKScoVY4qpOP%2BSXSdA46piOcSCairGFUFB3CMdCxsGsYlQQVYdjnmI5vtiPoR4KmmRTzYaL%2B9H64jwtz%2FPTp1XDvlf51l%2FZZWoZJI4WXdKYzTIYaqoxhMgVdzJU4Ibs8IIx0VDeaXDI%2Fm3YifNO3GhvbLBEZTSaWzHZImWGu9hs7%2B6d8tDSRWzKbgXZCuAKbL3agfhrr2ZaPqGYSTzZfoo3Vixfue8rESruv6NH7isbiTd9XNF7LfRcV0rgEMsoWPm1%2B8iiJP9ztOH5jUf49xNJ3FmWKurIVrhiLcDd3a9EY1kLFudlNQYejoj2gzk%2F49WwAmAMdTXZH2EsY9Wm8CBLoLgkrTXRGUqBCZ%2BWIlclbEmJYzkZebpCNGJ7S6rBFbR5vPWyTsb9ozWyzEXm82SBuuSVjsaup6Xr%2Bqw0WjQ12lwkQAeklbQKaHu%2BuADACcUzRl7sqCTFN5JhMxNBhrpZiVkExGXuOVkYxmYKm4xRnqA6O2pFD5ZZFgwgmsyVosmABgehlQXQIyC5pt1MkdlkOXgQil7Lg5LIcwAjDLYsFtVpuWWSz0XrJZbGNv86ZXI64hdF0csnY8wsugCnETlAFoSEgs6Q1gvDMMjdeBGKWdFJlyyzzA0YYZsnYmrCllpVQS8ZWo%2FVSS4l2Os9QIRzVvyX%2BjOjGk0vaACyB560d1zhDadej%2FnPAQzyCyfBGhCeY%2BQEjEMOkZ260DPMIxAhDMVWOkXFozGAkA4gnDW6eoAXw9oXX21%2F2Zlahj7%2Bc%2BwuLiAnaxoXrBmC6fkIweXbugb3pkNli258WwDa%2BBCjaFzM1GWs87qP%2FwpJvTPzFAZpoOBDBe87K1WEWZST9xo%2FIcdqNZHwZNwkvk2Eak%2FiiGzTlO9yrbwacHp0g8T4C6jAxeUwZJDAUfjp5aosfqqBRoiA5WVDYNFRBRwCxazy6s1tbd0bwk6xMvlm3DzPGShdf3eeszTHbGYdHzzjUBvuyVhmRdUXKQm0R%2F4cp%2FmLuzx%2Fu6fIYtsxOU2TCIVPQZfi5zBrTDlAj5htmYloov5fZEjQrxfseN2C2YQ3YaLLTy2waYdfUKwcoTXR2mS0j%2Bo4h5cCFuaZJXkpwQLHwFFcDYNp5hrVwTMY0w3o5ZiNmGWYiuGWUdOKFKOnfBYEhHJ1MG0KRJCGGUMqBizCkkpFy0bLK%2FHgRiFUylq%2B4Ma02bl3DSnkKa6m8EQMWUmVcs%2BCSFn%2B4U3G8m8qvUTKWymOJujpJ05SzwaFrIScEsEcsaP4o0JYwRdEhnLuh0ARS6PB1Ox0gFSkyhZTW1TgCMCxfIy8zyAYMT2l1AIYePBeIax4dNM3PNVkL5dXKNRV6wPzmVsoj7HOOYiv88zMaTy7pwe6GrMN8tAHIgQ7xyKWwyzCXBBVxyCUdlWzJ5RGAEYdcCh3IrJFcspbIq5dcNmIZk2wQt8wySvHfZZauEKuYFEWGcKxyQIcsgwwJWVXFTZHIDxhhuOWgDVyWAhhhuOUg5yRTROnmzsyxgVXTBFNovQV3YNmZOrCCItE3%2F5cgKDj5gU96anR69bH749WGgdbMNIl4DiuNryKzVjP9nrOZthpvuB0twDJMoJJ72up4v6A40%2FjAtFWECbDZuY14HakVlrREhSU1s17J%2BweDvfvRQViDcvsZx%2BrXJ5%2FMzehrBftG1kSIg10jaqKz6RrJGd2DpMLm7RrDUQKyyf1Cy5vR%2FXl0bawul%2B735Yf0GW5eFRusuyrtgXRkzcIm%2BA0dzPDBV3fiGLAHdAzAVz%2BY7x3egl4Z3xU%2F5qZfeZ6bHoaK67ybBsSH8MN3AfoX59Wh4wA0GBFzgI%2FXc0Q38BkMbjHwP0EJxsYGC1PvocN%2FgofmzsoysLDBO4yfmDoWIi6IRuCn546p40y7C56KRlcM8z15yaSeii6sITrsd9Hf7%2FDNM31chZenu6zGQteo8tA1xmtz1QRzm7Amz0Gj1l6BpTElFXi8ujnB%2B%2BG7T94fRLJOUIM38zepweXKwzmeGLYT4BonqMsaLCNgon7lgeXyBJUwFzNSiX8WYIY7f%2F2oWFgRKsLVYmuvQbqmKa0SRMfqAGvOt0BjLpYWXOAcYqwhza1GNf5F7ghWtwukWnHTYKRiKS03iNsH963Qo7g4xBN27iPKtJdWqRTv0nZ8TDU8wlkwS890%2ByTMLnZYzXqOlOo3dAt%2BfO0iVKMnfkJfn7N5vaHCkTHoMLjLSH5TNC2ua6GEZ0lKrNTBCkppLCdPzvAZeaPHbKvOsSblYV9uh0QSl35HFonFf3alEHtlUieXV0ZJaaiMr9WLLCntMsxMfrNLMZk3RmMEBynmx14FCvLIsboPHTnpYqXQP9qVSfoyCqezltvHiqd0RFXWDjhZBx4o7GWx5c5Kw0ooY0Jog4h7IT67NoMKBcqWENB%2FVx5uA3%2BN1auzxC9ic09zGqljDSywQrPfvOXJlWikGMDKd06mV%2FsJ4GxXWtzVrGqWm1e%2BZqWTvmrUrJVoSIXWkMxA1vgkCjIROpL6KpeCzK3W%2BsOEllLq0FKsmCvlfeMV1nrhzOmTqaluAHEkSZ39G3HIeWqD3X0DTsHK2vPcg2p5MKiOE7%2Bt1%2BpFmm8mgk%2BsleHYalGtTC3mDGryqkX4YfpxfB8db4kkJxVFz2zZJj7Z7Jw8QtdE3x9M5sxWr8dS2gJqWaXVcta033rVstSX9zGocerl0jQna50YZtzyWKV5McXAQB%2BE%2Fn59wsGbnfjjDNrQBYFDPYnuIW%2FrO2%2F%2FQp1WbboL8QM9nnenfErPXMyK0FWftgM7CjeMCSwBUiFB5NXdBlJ%2FuVHwFYduokbwkA1hfc%2BD44ePBjFcELzsF27K3UI8Wvf7jpuMUNxfX%2F2DrFH%2F6Uswdo1hFNXGay1BcvCgyww9sCwBtXBseZaAI0XxDyPIQ06CzDtIVaomHiUiCKN69bDGijQllBdeaaFX3MtOY4pJfph8nKlDggkceIpwq0aoFRtUXi1SnZutyYLwyZyJK8drsaijHk5DGZ1CjSW8b02tyM1PRElVYkG5M0SGNUQFNI7Y5QvSXz14aBSLgwzua1UyLhR755YzC9gYQhwIkY11LpLEPDhcmwFZDJ8KqhTtlMNFc58Tb4vHo5A2nOO8Fz3IeUEX%2FkLKVJ%2BHetsj6juMiJCRKfzeJXrv39Qn4fxF10TkuVX0SUXflRhr87A1%2FagyTV9R5KAWvpi1Vd7BESeNN9%2BvVEVLYSA5CMk74pQsKEk8yxpvSgSAZemAxk7c393X8NVo7BFrVCA52rRcBpFV5L7OcFYTS2vnV1Dx0mD5VdRhrTSdTmV2XuzNzaU6zCQkObzYpI1lzOyPt5XeVUqV%2BbCjnKnQEblMp5u9wS7hRMcG8OaxSjpSV8VCCH%2F5TppL3uOXPTnmlD86O%2FHL0glm1AcS6ozXb67aTU6MJQ44U5BL0xA5zVwqpCoGTnH5H3QwpFOYvXEyR0erN04yYoXF0iwE0HUkTT8lRU5II6EwZuTWbBQ4ZuT%2B4T2YwVwz9%2B6ttwsPxmpP1hRJHY7Gg6Gijfc6dM39OYIjV3%2BeIx%2FVgl6Qktn26EicVNbkqXv4OGfW5J%2FXwyPUHp5wc5JR5YGq9UZjTVWlISJoyijaiTktpbHqPs6xF0m5M7W207FOselm5lJ%2FB8MZY5kTMnXN0VITCmZw7K6bGhUErheHUj99kC1Iu98BpPZr5QTRXfjhd4m1wCYoNhjbWxjJBoyC3oD%2BcxaArquHMMPFmbaJ54kzy8NxYHRLtxsPzZHX9A8nZGTMbijpI6lwNPuVVM3OsKGxQpD7z1%2FQ%2F4LZnXI%2F0j3e3Dw0xYfxzaw7S%2FxsRFXskr78L9QhgjGATjTRheQzLsJ2CIHm%2Fb3zZeHbs5vhjMcHABxNmZRM00fwbVoOJVMTSV1dicXJWJtiVzcSzNotnbbCZYX%2FNe1Svrlhsq49i6xbwPNM%2FXlu2tFPxNpm7qJw0IjGqj6PFWUN2Kgl2dDk9OSj5zknJ4FUt3N1SsOmp1qfoWqPkwkD7R5tst3azVIalxjLoGlDGyqM3bzfs49J6%2BkEjRGirbWd%2BWynFJvAjH1varedPKMO52U7j82MCs6SCVhFDLF6VoY4OQ%2FqaGdWkhIJo7F3W5slTk%2FdP0NjsW%2BJw03DWjtctv8qmBn%2BQgxtuhVOJjWTNLdgRsXCCSbtfbGtTWy0MTBbk51zBCLh7qrREnintNg80yfO1WL39lJNtja6JovNO2ZxGtd5kAQNr8UeJHKjR0q9Q51Sn2fk%2B1wxmY5I3LV3MakOt%2FgtEZZR4ONMYEmtExJpnLyw7KpJ7Vkzj2TsGX3GZIeMirQsskIWKdooSPjpL%2BnjIBho7ShITlrYTUZyYtVbBS9Ep66DxbrVjaht5vfBSmvK9f8B

**Comment by dPetersLib** [comment]
![ER](https://user-images.githubusercontent.com/40390930/183618924-3a686547-d28f-488b-b71a-b711377b304c.png)
