### ISSUE TITLE
Grid System & Button System, Sign Up Page hifi (mobile and desktop), Sign up page lofi (mobile), Sign In page (mobile), Forgot Password pages (mobile), Final Design Review

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#8]
Upload your frame link.
Copy the particular frame link, you need to click on the frame you are trying to share before copying the link. The notification will be 'frame link copied' and not 'file link copied'.

**Comment by KenAkand** [comment]
Hello again.

**Comment by BabawaleSim** [comment]
Hello ,

**Comment by BabawaleSim** [comment]
**Grid Systems**

for Mobile: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=517%3A374
For tablet: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=517%3A380
For desktop: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=517%3A379

**Button System**
For all button states: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=517%3A9218

**Sign-up page hi-fi**
For Mobile: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A13436
For Desktop: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A7532

**Sign-up page lo-fi**
For mobile: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A3139

**Sign-in page hi-fi**
For mobile: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A14816

**Forget Password For mobile**
First Page: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A13464
Second Page: https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=2550%3A12144

And the general review of both hi-fi and lo-fi Desktop designs.
