### ISSUE TITLE
User Persona and User Story, Typography & Spacing System, Learn Page 2 lofi (mobile)

### ISSUE THREAD

**Issue by KenAkand** [zuri-training/Team-59_QRGen#9]

**Comment by benueplateaugirl** [comment]
@KenAkand, that's what I did. I did not get "the frame link copied" prompt. I tried severally.

**Comment by benueplateaugirl** [comment]
https://www.figma.com/file/8Vrbtq1xTftwm2bkfZ3b4N/Team-59_QrGen?node-id=599%3A317 Typography&Spacing
https://www.figma.com/file/N0Q8o15s5inpvlNN43lQ2C/Team-59_QrGen-UX?node-id=0%3A1 User Stories
https://www.figma.com/file/N0Q8o15s5inpvlNN43lQ2C/Team-59_QrGen-UX?node-id=0%3A1 User persona
